### ISSUE TITLE
[Enhancement] Correlation of own token should not replace with NaN

### ISSUE THREAD

**Issue by Filexor** [hnmr293/sd-webui-evviz2#1]
I found that correlation of own token is not always larger than correlation to other tokens and this information may useful.
So, I suggest to remove line 200 in scripts/evviz2.py .

**Comment by hnmr293** [comment]
Thank you for your feedback.
That is remarkable to me. I would be happy if you could give me an example of a reproducible model and prompt.

**Comment by Filexor** [comment]
Stable Diffusion Checkpoint: Elysium_V1.ckpt [abbb28cb5e] or v1-5-pruned-emaonly.ckpt [cc6cb27103]
Clip used: openai/clip-vit-large-patch14
Clip Skip: 1
Prompt: large amount of fluttery tiered layered frilled tulle robe
in "fluttery", 'flu' -> 't' has largest correlation value.

**Comment by hnmr293** [comment]
Oh!
I've fixed it. Thank you!
